urls.py
# Create URL patterns here
from . import views # the dot means same folder
from django.urls import path 
#from .views import HomePageView
app_name = 'tangyDjango'

urlpatterns = [
    path('',views.index, name='index'),
    path('item/', views.item, name='item'),
    path('<int:item_id>/', views.detail, name='detail'), # displaying an integer (the primary key) as the name of the page
    path('add', views.create_item, name='create_item'),
    #path('anotherPage/', views_1.anotherPage, name='another'),
    #path('templateView/', HomePageView.as_view(), name='home')
]

'''
the quotes would be empty for an empty path, index is the name of the path to views.index.
If something was in the quotations it would appear as tangyDjango/something in the localhost
'''

models.py
from django.db import models

# Create your models here.

# inheriting the model from the model class

class foodItems(models.Model):
    def __str__(self):
        return self.item_name
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default='https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg')
    

forms.py
from django import forms 
from .models import foodItems

class ItemForm(forms.ModelForm):
    class Meta:
        model=foodItems
        fields=['item_name','item_desc','item_price','item_image']

    

views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import foodItems
from django.template import loader
from .forms import ItemForm

# Create your views here.
def index(request):
    item_list=foodItems.objects.all()
    #template=loader.get_template('tangyDjango/index.html')
    context={
    'item_list':item_list
    }
    #return HttpResponse(template.render(context,request))
    return render(request, 'tangyDjango/index.html', context)
    
def Check(request):
    return HttpResponse('Hello Check')

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = foodItems.objects.get(pk = item_id)
    context = {
        'item':item,
    }
    return render(request, 'tangyDjango/detail.html', context)          

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('tangyDjango:index')
    return render(request, 'tangyDjango/item_form.html', {'form':form})                                  

templates/tangyDjango/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel = "stylesheet", href="{% static 'tangyDjango/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class = "navbar navbar-dark bg-light">
        <a href = "#" class = "navbar-brand" style = "color:#000000">Super Sausages</a>
        <div class="navbar">
            <a class = "nav-item nav-link" href = "{% url 'tangyDjango:create_item' %}">Add Item</a>
            <a class = "nav-item nav-link" href = "#">&nbsp;&nbsp;Delete Item</a>
            <a class = "nav-item nav-link" href = "#">&nbsp;&nbsp;View Item&nbsp;&nbsp;</a>
        </div>
    </nav>
    {% block body %}

    {% endblock %}
</body>
</html>

templates/tangyDjango/detail.html

{% extends 'tangyDjango/base.html' %}
{% block body %}

<div class = "container">
    <div class = "row">
        <div class = "col-md-6">
            <img src = "{{item.item_image}}", width = "500", height="500", class = "wdn-stretch rounded corners"/>
        </div>
        <div class = "col-md-6">
    <h1>{{item.item_name}}</h1>
    <h2>{{item.item_desc}}</h2>
    <h3>{{item.item_price}}</h3> 
        </div> 
    </div>
</div>
{% endblock %}

templates/tangyDjango/index.html

{% extends 'tangyDjango/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% for item in item_list %}

    <div class = "row">
        <div class = "col-md-3 offset-md-1">
            <img class = "card" height = "150px" width = "500px" src = "{{item.item_image}}">
        </div>
        <div class = "col-md-4 offset-md-2">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>{{item.item_price}}</h3>
        </div>
        <div class = "col-md-2">
            <a href = "{% url 'tangyDjango:detail' item.id %}" class = "btn btn-success">Details</a>
        </div>
    </div>

    {% endfor %}
    {% endblock %}

    <ul>
        <li><a href = "{% url 'tangyDjango:detail' item.id %}">{{item.id}} -- {{item.item_name}}</a></li>
    </ul>

</body>
</html>


templates/tangyDjango/item_form.html
{% extends 'tangyDjango/base.html' %}
{% block body %}
<form method = "POST">
    {% csrf_token %}
    {{ form }}
    <button type = "submit">
        Save
    </button>
</form>
{% endblock %}

templates/tangyDjango/templates.html
<h1>Home Page</h1>